a=int(input("Enter a"))
b=int(input("Enter b"))
c1=a+b
c2=a-b
c3=a*b
c4=a/b
c5=a%b
c6=a//b
print(a,"+",b,"=",c1)
print(a,"-",b,"=",c2)
print(a,"*",b,"=",c3)
print(a,"/",b,"=",c4)
print(a,"%",b,"=",c5)
print(a,"//",b,"=",c6)
